/*
 * This source file was generated by the Gradle 'init' task
 */
package moneypractice;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static moneypractice.Currency.*;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

public class MoneyTest {

    @ParameterizedTest(name = "{3}")
    @CsvSource({
            "USD, 1.10, USD 1.10, Both positive & cents > 9",
            "PHP, 1.0, PHP 1.00, Both positive & cents = 0",
            "USD, 0.10, USD 0.10, Dollar = 0",
            "EUR, 0.0, EUR 0.00, Both dollar and cents = 0",
            "EUR, -1.10, EUR -1.10, Negative dollar & cents > 9",
            "USD, -0.01, USD -0.01, Negative & dollar = 0",
    })
    void toString_ShouldFormatCorrectly_ForVariousValidValues(Currency currency, float value, String expectedValue,
            String description) {
        Money money = new Money(currency, value);
        String actualValue = money.toString();
        System.out.printf("Expected: %s, Actual: %s%n", expectedValue, actualValue);
        assertEquals(expectedValue, actualValue, "Test failed for: " + description);
    }

    @Test
    void toString_ShouldTruncateCentsCorrectly_WhenValueHasExcessPrecision() {
        Money money = new Money(USD, 1.9999f);
        String expectedValue = "USD 1.99";
        String actualValue = money.toString();
        System.out.printf("Expected: %s, Actual: %s%n", expectedValue, actualValue);
        assertEquals(expectedValue, actualValue, "Test failed for rounding cents");
    }

    @Test
    void constructor_ShouldThrowException_ForInvalidCurrency() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Money(Currency.valueOf("CAD"), (float) -2.02);
        });
    }

    @ParameterizedTest(name = "{3}")
    @CsvSource({
            "USD, 1.10, 1.10, 2.20, Both positive & cents > 9",
            "PHP, 1.0, 1.0, 2.00, Both positive & cents = 0",
            "USD, 0.10, 0.10, 0.20, Dollar = 0",
            "EUR, -1.10, -1.10, -2.20, Negative dollar & cents > 9",
            "USD, -0.01, -0.01, -0.02, Negative & dollar = 0",
            "USD, 1.10, -1.10, 0.00, Positive & negative",
    })
    void add_ShouldReturnCorrectSum_ForValidMoneyValues(Currency currency, float value1, float value2, float expectedValue, String description) {
        Money money1 = new Money(currency, value1);
        Money money2 = new Money(currency, value2);
        Money result = money1.add(money2);
        Money expected = new Money(currency, expectedValue);
        System.out.printf("Expected: %s, Actual: %s%n", expected, result);
        assertEquals(expected, result, "Test failed for: " + description);
    }

    @ParameterizedTest(name = "{3}")
    @CsvSource({
            "USD, 1.10, 1.10, 0.00, Both positive & cents > 9",
            "PHP, 1.0, 1.0, 0.00, Both positive & cents = 0",
            "USD, 0.10, 0.10, 0.00, Dollar = 0",
            "EUR, -1.10, -1.10, 0.00, Negative dollar & cents > 9",
            "USD, -0.01, -0.01, 0.00, Negative & dollar = 0",
            "USD, 1.10, -1.10, 2.20, Positive & negative",
            "PHP, -1.10, 0.05, -1.15, Negative Cents"
    })
    void subtract_ShouldReturnCorrectDifference_ForValidMoneyValues(Currency currency, float value1, float value2, float expectedValue, String description) {
        Money money1 = new Money(currency, value1);
        Money money2 = new Money(currency, value2);
        Money result = money1.subtract(money2);
        Money expected = new Money(currency, expectedValue);
        System.out.printf("Expected: %s, Actual: %s%n", expected, result);
        assertEquals(expected, result, "Test failed for: " + description);
    }

    @Test
    void testAdd_different_currencies() {
        Money money1 = new Money(USD, 10.12F);
        Money money2 = new Money(PHP, 2.19F);
        assertThrows(IllegalArgumentException.class, () -> {
            money1.add(money2);
        });
    }
    @Test
    void testSubtract_different_currencies() {
        Money money1 = new Money(USD, 180.62F);
        Money money2 = new Money(EUR, 21.49F);
        assertThrows(IllegalArgumentException.class, () -> {
            money1.subtract(money2);
        });
    }
}